### PR TITLE
Add options to handle wrapped classes to extend the set of use cases

### LINKED ISSUE #108: Make viable for more use cases
The `custom-regex` option is great, but it's still only possible to use this when the classes can be in a capture group with nothing else but spaces in between them (at least from all I've tried)

More options would allow Rustywind to be used when the classes are in the files, not as space-separated lists. This needs more than a simple addition but more reworking of the sorter.

Here is a single example of where it would be nice to use.
`classes = ["flex", "flex-col", "rounded-xl", "border", "border-teal-600", "p-4", "w-[var(--rhs-width)]"]`

Maybe another regex could be used after we have extracted the part that has all the classes (which is the current settable regex) and another that matches each single classes (although then one would also need to define something like a pre- and suffix for a class entry)
Honestly I do not have a good (UX-wise) way in mind to do that.

If you have a better idea and/or would want this feature in rustywind, I'd be happy to also spend some time on implementation.

### PR DESCRIPTION
**Pull request by dikkadev**
As discussed in #108, a new CLI option, `class_wrapping`, is added to cover more use cases in combination with the existing `custom_regex` option.

If the option is not supplied, the default value is used, and the behavior is not changed from before.

Fixes #108

### CODE REVIEW

**Comment by praveenperera** [comment]
Hey @Sett17 sorry I just saw this, could you resolve conflicts and add some tests and I’ll merge this in? 

Thank you!

**Comment by Sett17** [comment]
> add some tests

Hey, I've already added some tests:
https://github.com/avencera/rustywind/blob/f56ca30359194c1c3ab808616989fb5747c75b65/rustywind-core/src/sorter.rs#L514-L607

Are more or different tests needed?

**Comment by Sett17** [comment]
Let me know if this works for you; I can remember having some problems with the workspace setup when I made the changes (although it was 2 months ago, so I probably don't remember it 100%)

**Comment by praveenperera** [comment]
Thanks @dikkadev, merged, will release 0.23 with this

**Pull request merged**
