### PR TITLE
Read from stdin

### LINKED ISSUE #19: Getting source code from stdin
Hi!

thanks for the tool!

I would like to request a feature, an optional ... option jaja, for receiving source code from stdin, and easy a bit integrating the tool with Emacs via [reformatter.el](https://github.com/purcell/reformatter.el#define-commands-which-run-reformatters-on-the-current-emacs-buffer), right now the reformatting part can run before the file is even written to disk, thus triggering an error in `rustywind`:

```
~ via ⬢ v15.5.0
➜ echo "" | rustywind
RustyWind 0.7.0
Praveen Perera <praveen@avencera.com>

Organize all your tailwind classes

USAGE:
    Run rustywind with a path to get a list of files that will be changed
      rustywind . --dry-run

    If you want to reorganize all classes in place, and change the files run with the `--write` flag
      rustywind --write .

    rustywind [FLAGS] <PATH>

FLAGS:
        --allow-duplicates    When set, rustywind will not delete duplicated classes
        --dry-run             Prints out the new file content with the sorted classes to the terminal
    -h, --help                Prints help information
    -V, --version             Prints version information
        --write               Changes the files in place with the reorganized classes

ARGS:
    <PATH>    A file or directory to run on
~ via ⬢ v15.5.0
✖ echo $?
1
```

For the time being I'm passing the full path of the file, that should work, but in this edge cases where there is no file on disk yet, making `reformatter.el` trigger an error (rightly so).

### PR DESCRIPTION
**Pull request by praveenperera**
Closes #19

### CODE REVIEW

**Comment by praveenperera** [comment]
@shackra now if a class isn't found in STDIN it will print the original contents and a error

```bash
$ echo "hello" | rustywind --stdin
hello

[ERROR] No classes were found in STDIN

```

**Comment by shackra** [comment]
Well, from an "integrate everything with Emacs" point of view, returning `2` on error is good enough, if you can return `[ERROR] No classes were found in STDIN` to stderr people may appreciate that, so users don't accidentally litter their source code with a banner at the end of it (in case whatever they are doing is not checking the return value of the `rustywind` command)

other than that, this PR is good to go.

**Comment by praveenperera** [comment]
Right now 

`hello` (or whatever was passed in via STDIN is printed to STDOUT

and 

`[ERROR] No classes were found in STDIN` is printed to STDERR

**Comment by shackra** [comment]
oh, btw, two blank lines were inserted in the output :grimacing: 

Maybe you want to check that?

**Comment by shackra** [comment]
Let me explain, I did this for testing:

```
✖ echo '<div classNames="px-2 border-0 text-green-200" />' | ./rustywind --stdin > /tmp/prueba.txt
[ERROR] No classes were found in STDIN
```

Which is cool.

but the file generated contains the line of code plus two blank lines that did not exist in the original input: 
[prueba.txt](https://github.com/avencera/rustywind/files/5792132/prueba.txt)

**Comment by praveenperera** [comment]
@shackra thanks good catch, its fixed now: https://github.com/avencera/rustywind/commit/d1f3c5429c7593ff78b4e79054eeb371a27aeda5

New version (v0.8.0) is released

**Pull request merged**
