### PR TITLE
Fix #67: Download is rate-limited by GitHub

### LINKED ISSUE #67: Downloading rustywind failed: Error: Request failed: 403
Hi, @artemkovalyov Thank you for your fantastic work. 

I got the below error on my GitHub Action. I'm not sure how to solve this the way it needs to download files based on the os at runtime.

```sh
error /node_modules/rustywind: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments: 
Directory: /node_modules/rustywind
Output:
Finding release for v0.15.1
GET https://api.github.com/repos/avencera/rustywind/releases/tags/v0.15.1
Deleting invalid download cache
Downloading rustywind failed: Error: Request failed: 403
```

### PR DESCRIPTION
**Pull request by adamdicarlo0**
Store release JSON data in repository, and use it to download rustywind.

We still use the GitHub API when downloading rustywind; if it fails, we try downloading from the "browser download url" which is not on GitHub's api subdomain. Whether this fall-back will actually help depends on how GitHub's rate-limiting works.

### CODE REVIEW

**Comment by praveenperera** [comment]
Thanks @adamdicarlo0 lets try it out

**Comment by jellydn** [comment]
Great. Thanks.  Could you draft a release?

**Comment by praveenperera** [comment]
@jellydn released

**Comment by adamdicarlo0** [comment]
@praveenperera Sorry, I broke the published npm package! 😳 

#69 should fix it! But you will have to make sure to create the new GitHub release before running `npm publish`. (I don't know if you do these steps manually or not.)

**Comment by jellydn** [comment]
I often use [sindresorhus/np: A better `npm publish`](https://github.com/sindresorhus/np) to release a pre-release version then test it again before bump to next version, FYI :)

**Pull request merged**
