### PR TITLE
fix(build): Fix npm publishing

### PR DESCRIPTION
**Pull request by adamdicarlo0**
Pull request #68 broke the npm package; the release.json file in the package contains the release data from the *previous* rustywind release.

Now we'll automatically run the `update-release.js` script when publishing the package (and when running `npm pack`).

**The GitHub release now must be created *before* running `npm publish`** so that the published package can contain the latest release info.

-----

I tested this by publishing to a test package [rustywind-publishing-test](https://www.npmjs.com/package/rustywind-publishing-test). I'll delete the package once this is all resolved.

### CODE REVIEW

**Comment by praveenperera** [comment]
@adamdicarlo0 missing `release.json`

**Comment by praveenperera** [comment]
Got it working had to run `npm run prepack && npm publish`. thanks @adamdicarlo0

**Comment by adamdicarlo0** [comment]
@praveenperera in my testing, the `prepack` script would be run automatically by `npm publish`. I tested with `rm release.json; npm publish`. I'm testing on npm 8.x though, because that's what we use on my work project... it's possible that the version you're using doesn't call prepack? 😬

**Comment by praveenperera** [comment]
I'm on npm 9.x

**Pull request merged**
