### PR TITLE
Match sorting rules to tailwind prettier plugin

### PR DESCRIPTION
**Pull request by praveenperera**
Closes: #75

@Cretezy @tobimori can you help me test this, you can build locally by running `./local-release`

To get this working you need to run it with `--output-css-file=<PATH TO OUTPUT CSS FILE>` to point to the final css file generated by tailwind css.

### CODE REVIEW

**Comment by tobimori** [comment]
One thing to keep in mind:
There are certain setups where it's impossible to have an output file in development mode, e.g. using Vite. Vite's assets are usually available under a certain web address. Can you implement a way to fetch a remote resource for the sort order?

**Comment by praveenperera** [comment]
@tobimori if this works yes I can do that later, but one step at a time

**Comment by tobimori** [comment]
> @tobimori if this works yes I can do that later, but one step at a time

Can't test it without - sorry, I only use Tailwind together with Vite.

**Comment by praveenperera** [comment]
@tobimori can you do a production build so if spits out a css file just to test it out?

**Comment by praveenperera** [comment]
@tobimori I ran vite and it shows the location of css file


Screenshot 2023-08-11 at 12 53 03 PM

**Comment by tobimori** [comment]
This is the source file (which doesn't contain the class order)

**Comment by praveenperera** [comment]
@tobimori I added support for vite: https://github.com/avencera/rustywind/releases/tag/v0.18.0

`rustywind --vite-css <PATH> .`

**Comment by tobimori** [comment]
thanks! i'm on vacation right now but will test it asap 😍

**Pull request merged**
