### PR TITLE
update default config

### PR DESCRIPTION
**Pull request by dhrubabasu**
config copied from https://github.com/heybourn/headwind/blob/master/package.json

### CODE REVIEW

**Comment by praveenperera** [comment]
Looks good, can you fix the failing tests? And then I will merge it in

**Comment by dhrubabasu** [comment]
@praveenperera Passes appveyor, travis hasn't started yet :(

**Comment by praveenperera** [comment]
Looks good thanks @dhrubabasu. I am going to merge now. And will make a new release once travis finishes building.

Thanks!
❤️ 🥳 👍

**Comment by praveenperera** [comment]
@dhrubabasu I've published a new version (0.7.0) with these changes

**Pull request merged**
